---
#
# Manages system wide settings (locale, packages)
#
# DEBUG: run with --extra-vars="playbook_debug=yes"
#
# USAGE:
# See the defaults variables
#
# - {
#     role: system,
#     system_packages: ["git"],
#     system_locale: "en_US.UTF-8",
#   }

### DEBUG
- name: debug
  debug: msg={{ system_locale }} {{ system_packages }}
  when: playbook_debug is defined and playbook_debug
#######


- name: ensure packages state
  sudo: yes
  apt: name={{item.name | default(item)}} state={{item.state | default('present')}} update_cache=yes cache_valid_time=7200
  with_items: system_packages

- name: set locale
  sudo: yes
  command: /usr/sbin/update-locale LANG={{system_locale}} LC_ALL={{system_locale}}
